export type DateRange = [Date, Date] | null

export const texts = {
    "common.loading": "Carregando...",
    "404.title": "Não encontrado",
    "404.link": "Retornar para o início",
    "home.navbar.title": "Vacation Planner",
    "home.navbar.login": "Login",
    "home.panel.subtitle":
        "Quem nunca tirou férias e fez 1001 planos para aproveitar o máximo e quando piscou o olho não fez nada e as férias já estavam no fim?!",
    "home.panel.description":
        "Com o Vacation Planner você tem mais controle dos seu dias de férias. Tirando os planos da cabeça e colocando no planner, você terá maior controle do planejamentoda suas férias podendo até compartilhar seus compromissos com outras pessoas",
    "home.insert.days": "Para começar planejar suas férias insira a o período desejado abaixo:",
    "home.calendar.invalid.date.selection": "O dia {{}} não pertence ao período selecionado",
    "home.calendar.events.count": "Ver os {{}} eventos",
    "login.form.login.title": "Realize seu login",
    "login.form.newHere.label": "Novo por aqui?",
    "login.form.newHere.link": "Novo por aqui?",
    "login.form.create.title": "Cadastre-se",
    "login.form.login": "Login",
    "login.form.create": "Cadastrar",
    "login.form.username.label": "Nome de usuário",
    "login.form.username.placeholder": "Digite aqui seu nome de usuário",
    "login.form.username.required": "Seu nome de usuário deve ser preenchido",
    "login.form.password.label": "Senha",
    "login.form.password.placeholder": "Digite sua senha aqui",
    "login.form.password.display": "Mostrar a senha",
    "login.form.password.required": "A senha não pode ser deixada em branco",
    "login.form.password.length": "Sua senha possue ao menos 6 caracteres",
    "login.notification.success": "Login efetuado com sucesso! Você será redirecionado em um segundo...",
    "login.notification.failure": "Nome de usuário ou senha incorretos!",
    "login.notification.error": "Um erro ocorreu ao tentar realizar o login. Recarregando a página...",
    "login.notification.empty": "Preencha os campos antes de prosseguir!",
    "modal.calendar.event.name": "Nome do evento",
    "modal.calendar.event.name.description": "Digite o nome do evento",
    "modal.calendar.event.time": "Hora do evento",
    "modal.calendar.event.time.description": "Selecione a hora do evento",
    "modal.calendar.event.participants": "Adicionar pareticipantes ao evento",
}
